### ISSUE TITLE
Починить апи локаций

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/phoqer#149]
​/locations​/countries​/
/locations/cities/{slug}

**Comment by MarianMalvin** [comment]
Скорее всего дело не в КОРСАХ, тут похоже на то, что в нашей бд на проде нету полей нужных в БД
```
backend     | INFO:     192.168.160.6:54074 - "GET /api/v2/locations/countries/ HTTP/1.0" 500 Internal Server Error
backend     | ERROR:    Exception in ASGI application
backend     | Traceback (most recent call last):
backend     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
backend     |     result = await app(self.scope, self.receive, self.send)
backend     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend     |     return await self.app(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
backend     |     await super().__call__(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
backend     |     await self.middleware_stack(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend     |     raise exc from None
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend     |     await self.app(scope, receive, _send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
backend     |     await self.app(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend     |     raise exc from None
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend     |     await self.app(scope, receive, sender)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
backend     |     await route.handle(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
backend     |     await self.app(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
backend     |     response = await func(request)
backend     |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
backend     |     raw_response = await run_endpoint_function(
backend     |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
backend     |     return await dependant.call(**values)
backend     |   File "/phoqer/FastAPI/locations/locations.py", line 14, in return_countries
backend     |     countries = await crud.get_countries()
backend     |   File "/phoqer/FastAPI/locations/crud.py", line 7, in get_countries
backend     |     return await database.fetch_all(query=query)
backend     |   File "/usr/local/lib/python3.8/site-packages/databases/core.py", line 140, in fetch_all
backend     |     return await connection.fetch_all(query, values)
backend     |   File "/usr/local/lib/python3.8/site-packages/databases/core.py", line 239, in fetch_all
backend     |     return await self._connection.fetch_all(built_query)
backend     |   File "/usr/local/lib/python3.8/site-packages/databases/backends/postgres.py", line 160, in fetch_all
backend     |     rows = await self._connection.fetch(query, *args)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 443, in fetch
backend     |     return await self._execute(query, args, 0, timeout)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1445, in _execute
backend     |     result, _ = await self.__execute(
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1454, in __execute
backend     |     return await self._do_execute(query, executor, timeout)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1466, in _do_execute
backend     |     stmt = await self._get_statement(query, None)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 351, in _get_statement
backend     |     statement = await self._protocol.prepare(stmt_name, query, timeout)
backend     |   File "asyncpg/protocol/protocol.pyx", line 163, in prepare
backend     | asyncpg.exceptions.UndefinedTableError: relation "countries" does not exist
backend     | INFO:     192.168.160.6:54076 - "GET /api/v2/locations/countries/ HTTP/1.0" 500 Internal Server Error
backend     | ERROR:    Exception in ASGI application
backend     | Traceback (most recent call last):
backend     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
backend     |     result = await app(self.scope, self.receive, self.send)
backend     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend     |     return await self.app(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
backend     |     await super().__call__(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
backend     |     await self.middleware_stack(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend     |     raise exc from None
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend     |     await self.app(scope, receive, _send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
backend     |     await self.app(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend     |     raise exc from None
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend     |     await self.app(scope, receive, sender)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
backend     |     await route.handle(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
backend     |     await self.app(scope, receive, send)
backend     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
backend     |     response = await func(request)
backend     |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
backend     |     raw_response = await run_endpoint_function(
backend     |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
backend     |     return await dependant.call(**values)
backend     |   File "/phoqer/FastAPI/locations/locations.py", line 14, in return_countries
backend     |     countries = await crud.get_countries()
backend     |   File "/phoqer/FastAPI/locations/crud.py", line 7, in get_countries
backend     |     return await database.fetch_all(query=query)
backend     |   File "/usr/local/lib/python3.8/site-packages/databases/core.py", line 140, in fetch_all
backend     |     return await connection.fetch_all(query, values)
backend     |   File "/usr/local/lib/python3.8/site-packages/databases/core.py", line 239, in fetch_all
backend     |     return await self._connection.fetch_all(built_query)
backend     |   File "/usr/local/lib/python3.8/site-packages/databases/backends/postgres.py", line 160, in fetch_all
backend     |     rows = await self._connection.fetch(query, *args)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 443, in fetch
backend     |     return await self._execute(query, args, 0, timeout)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1445, in _execute
backend     |     result, _ = await self.__execute(
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1454, in __execute
backend     |     return await self._do_execute(query, executor, timeout)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1466, in _do_execute
backend     |     stmt = await self._get_statement(query, None)
backend     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 351, in _get_statement
backend     |     statement = await self._protocol.prepare(stmt_name, query, timeout)
backend     |   File "asyncpg/protocol/protocol.pyx", line 163, in prepare
backend     | asyncpg.exceptions.UndefinedTableError: relation "countries" does not exist
```

**Comment by EgorFray** [comment]
Игорь проверил, сказал что всё хорошо
